# Generated by Django 4.0.6 on 2022-07-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=10000)),
                ('Phone', models.CharField(max_length=50)),
                ('contact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='homeapi/images')),
                ('category', models.CharField(default='', max_length=50)),
                ('label', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('dishId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=5)),
                ('comment', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
